### ISSUE TITLE
Wrong type hint for AwsQuantumTaskBatch results

### ISSUE THREAD

**Issue by sterseba** [amazon-braket/amazon-braket-sdk-python#1038]
**Describe the bug**
The type hint of the return statement in the methods [`results()`](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/36e32f63d33a97b8b17addb0e90b692cda93b4ae/src/braket/aws/aws_quantum_task_batch.py#L329) and [`_retrieve_results()`](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/36e32f63d33a97b8b17addb0e90b692cda93b4ae/src/braket/aws/aws_quantum_task_batch.py#L372) in `braket.aws.aws_quantum_task_batch.AwsQuantumTaskBatch` is `list[AwsQuantumTask]`. Both methods return instances of `list[Union[GateModelQuantumTaskResult, AnnealingQuantumTaskResult, PhotonicModelQuantumTaskResult]]`, instead.

**To reproduce**
```python
from braket.aws import AwsDevice
from braket.circuits import Circuit
from braket.devices import Devices
from typing import get_type_hints

my_circuit = Circuit().x(0)
device = AwsDevice(Devices.Amazon.SV1)
batch = device.run_batch([my_circuit], shots=10)
print(get_type_hints(batch.results)["return"])

results = batch.results()
print(type(results), type(results[0]))
```

**Expected behavior**
The return type hints of both methods should match the actual return type.

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.88.0
- **Amazon Braket Python Schemas version**: 1.22.1
- **Amazon Braket Python Default Simulator version**: 1.26.0
- **Python version**: 3.10.12

**Comment by math411** [comment]
Hi @sterseba, thank you for pointing this out.

https://github.com/amazon-braket/amazon-braket-sdk-python/pull/1039 was published to fix this issue.

**Comment by rmshaffer** [comment]
Closing this since #1039 has been merged. Thanks @sterseba for reporting and @math411 for fixing!
