### ISSUE TITLE
Is `pulse_gate` not a gate (i.e. in supported operations)?

### ISSUE THREAD

**Issue by Qottmann** [amazon-braket/amazon-braket-sdk-python#541]
**What did you find confusing? Please describe.**
I am looking for the device property that describes whether or not a device has pulse level control access. I was assuming that the list of supported operations would contain `pulse_gate`, but for one of the two devices where that is the case, I cannot find it:
```python
device = AwsDevice("arn:aws:braket:eu-west-2::device/qpu/oqc/Lucy")
supported_ops = device.properties.action["braket.ir.openqasm.program"].supportedOperations
print(supported_ops)
```
```pycon
['ccnot', 'cnot', 'cphaseshift', 'cswap', 'cy', 'cz', 'h', 'i', 'phaseshift', 'rx', 'ry', 'rz', 's', 'si', 'swap', 't', 'ti', 'v', 'vi', 'x', 'y', 'z', 'ecr']
```

**Describe how documentation can be improved**
It would be great to have more details about how `pulse_gate` is treated on braket python sdk, we need it for the pennylane braket plugin to allow pulse gates.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by christianbmadsen** [comment]
@Qottmann Thank you for raising this request. At the moment you would need to do something like a "Try Except" statement on "device.properties.pulse" in Python.

**Comment by ajberdy** [comment]
To add to the above, if you'd like to avoid a Try/Except, you can also check if the device properties contains a pulse entry with `"pulse" in device.properties.dict()`
