### ISSUE TITLE
Add matrix representation of gates to docstrings

### ISSUE THREAD

**Issue by kshitijc** [amazon-braket/amazon-braket-sdk-python#597]
**What did you find confusing? Please describe.**
The documentation for the supported gates don't sufficiently describe the action of these gates or how each of the parameters are used. 

**Describe how documentation can be improved**
The docstring for each gate implemented [here](https://github.com/aws/amazon-braket-sdk-python/blob/main/src/braket/circuits/gates.py) should show the matrix representation of the gate. 

**Additional context**

**Comment by math411** [comment]
As a point of discussion for the issue, it would seem to make sense to have the docstrings using the [math](http://www.pythondoc.com/sphinx/ext/math.html#directive-math) directive so they render correctly in the docs.

**Comment by speller26** [comment]
For reference, look at how gate matrices are written in the [PennyLane plugin](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/src/braket/pennylane_plugin/ops.py#L59-L69)

**Comment by ykharkov** [comment]
Closing the issue, since the PR addressing the issue was merged: https://github.com/amazon-braket/amazon-braket-sdk-python/pull/756
