### ISSUE TITLE
Unsupported GateModifer: 'ctrl'

### ISSUE THREAD

**Issue by ryanhill1** [amazon-braket/amazon-braket-sdk-python#683]
**Describe the bug**

Exception raised when submitting quantum task using circuit with control modifiers

**To reproduce**

```python
from braket.aws import AwsDevice
from braket.circuits import Circuit

circuit = Circuit().y(target=0, control=1)

device = AwsDevice("arn:aws:braket:::device/quantum-simulator/amazon/sv1")

task = device.run(braket_circuit, shots=100)
```
```python
ValidationException: An error occurred (ValidationException) when calling the CreateQuantumTask operation: [line 4] uses an unsupported GateModifer: 'ctrl'
```

**Expected behavior**

Task should be submitted without exception

**Screenshots or logs**

N/A

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.54.1
- **Amazon Braket Python Schemas version**: 1.19.1
- **Amazon Braket Python Default Simulator version**: 1.20.0
- **Python version**: 3.9.15

**Additional context**

N/A

**Comment by math411** [comment]
Hi @ryanhill1, could you please try using the `LocalSimulator` to run the circuit? Currently, gate modifiers are [supported](https://docs.aws.amazon.com/braket/latest/developerguide/braket-openqasm-supported-features.html#braket-openqasm-supported-features-advanced-feature-local-simulator) for this device. 

The following is a code snippet that you can swap out your `device` object for:
```
from braket.devices import LocalSimulator
device = LocalSimulator()
```
For more information, running circuits on a `LocalSimulator` can be found [here](https://docs.aws.amazon.com/braket/latest/developerguide/braket-send-to-local-simulator.html).

**Comment by ryanhill1** [comment]
@math411 Oh ok, wasn't aware the feature wasn't supported for remote devices yet. Yeah, it works for the `LocalSimulator` and gives a warning about running on QPUs.

**Comment by shpface** [comment]
Yes, this makes sense. We will adjust the error messaging upstream to be more descriptive and more useful. Thanks for the feedback!

**Comment by laurencap** [comment]
Hi Ryan! The error message returned from the service has been updated.

When I run the repro code today, I get:
```
ValidationException: An error occurred (ValidationException)
when calling the CreateQuantumTask operation: [line 4] device
arn:aws:braket:::device/quantum-simulator/amazon/sv1 does not
support GateModifer 'ctrl'
```

Thanks again for raising this issue!
