### ISSUE TITLE
Queue Position / Queue Depth create quantum task bug

### ISSUE THREAD

**Issue by ryanhill1** [amazon-braket/amazon-braket-sdk-python#736]
**Describe the bug**

When I create (run) a quantum task on Aquila value of my queue position is larger than the value of the device queue depth.

Might be true for other devices as well, but haven't checked.

**To reproduce**

```python
device = AwsDevice("arn:aws:braket:us-east-1::device/qpu/quera/Aquila")

task = device.run(ahs_program, ...)

print(task.queue_position().queue_position)
# 71

queue_depth_info = device.queue_depth()
queued_tasks = queue_depth_info.quantum_tasks
print(queued_tasks["Normal"])
# 70
```

**Expected behavior**
Task queue position on a device shouldn't be greater than the total device queue depth.

**System information**
- **Amazon Braket Python SDK version**: 1.56.0
- **Amazon Braket Python Schemas version**: 1.19.1.post0
- **Amazon Braket Python Default Simulator version**: n/a
- **Python version**: 3.9.16

**Comment by mdpratt** [comment]
Hi @ryanhill1, we've flagged this process to be improved internally. In the meantime, we're going to improve our documentation to let customers know that these numbers are approximate.
