### ISSUE TITLE
from_ir method for AnalogHamiltonianSimulation

### ISSUE THREAD

**Issue by peterkomar-aws** [amazon-braket/amazon-braket-sdk-python#971]
**Describe the feature you'd like**
The [braket.ahs.AnalogHamiltonianSimulation](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/ahs/analog_hamiltonian_simulation.py#L28) object has a [to_ir method](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/ahs/analog_hamiltonian_simulation.py#L52) to export its content in the format of [braket.ir.ahs.Program](https://github.com/amazon-braket/amazon-braket-schemas-python/blob/main/src/braket/ir/ahs/program_v1.py#L34), but no `from_ir` method, which would load the content of an `braket.ir.ahs.Program` object into a `braket.ahs.AnalogHamiltonianSimulation` object. Let's create this method so AHS programs can be worked with similarly to circuits (See [braket.circuits.Circuit.from_ir](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/circuits/circuit.py#L1262))

**How would this feature be used? Please describe.**
There are two common use cases:

1. We start from a results.json file, which is created by the Braket service after successfully running an AHS program. The metadata content of such a file contains the ahs program that was run and it can be loaded as a `braket.ir.ahs.Program` object, after which we can call `braket.ahs.AnalogHamiltonianSimulation.from_ir()` to create the AHS program in the Braket SDK's abstractions. This allows us to modify and inspect it using the utilities in the Braket SDK.

2. We start from an ahs_program.json file, which we created previously when we serialized by `braket.ahs.AnalogHamiltonianSimulation` object with `my_ahs_program.to_ir().json()`, and written to a file. At a later point, we read the json file to a dict `json_dict` and recreate the AHS object with `my_ahs_prgram = AnalogHamiltonianSimulation.from_ir(Program(json_dict))`.

**Describe alternatives you've considered**
The alternative is to develop utilities to edit and inspect a `braket.ir.ahs.Program` object, instead of the already established standard representation `braket.ahs.AnalogHamiltonianSimulation`.

**Comment by king-p3nguin** [comment]
Hi, I would like to work on this issue for unitaryhack.

**Comment by peterkomar-aws** [comment]
https://github.com/amazon-braket/amazon-braket-sdk-python/pull/983 resolves this issue. Thank you, @king-p3nguin
